package main

import "io"

var envTemplateUnix string = `
########################################
#
# This file is generated by goautoenv
#
# Please do not change this file.
#

ENV_DIR={{.Env.Root}}

GOPATH_OLD=${GOPATH}
GOPATH={{.Env.GOPATH}}
export GOPATH

_GOAUTOENV_OLD_PATH=${PATH}
PATH=${GOPATH}/bin:${PATH}
export PATH

GOPACKAGE_OLD=${GOPACKAGE}
GOPACKAGE={{.Env.Package}}
export GOPACKAGE

_GOAUTOENV_WORKSPACE=${GOPATH}/src/${GOPACKAGE}

_OLD_GOAUTOENV_PS1="$PS1"
PS1="($GOPACKAGE)\n$PS1"

{{range $e := .Aliases}}
_GOAUTOENV_{{$e}}=$(which {{$e}})

{{$e}} () {
  pushd $_GOAUTOENV_WORKSPACE > /dev/null 2>&1
  $_GOAUTOENV_{{$e}} $@
  popd > /dev/null 2>&1
}
{{end}}

deactivate () {
  GOPATH=$GOPATH_OLD
  export GOPATH
  GOPACKAGE=$GOPACKAGE_OLD
  export GOPACKAGE
  PATH=${_GOAUTOENV_OLD_PATH}
  export PATH
  PS1=$_OLD_GOAUTOENV_PS1
  export PS1

  unset -f deactivate
  {{range $e := .Aliases}}
  unset -f {{$e}}
  unset _GOAUTOENV_{{$e}}
  {{end}}
}
`

func WriteEnvUnixFile(env *Environment, writer io.Writer) error {
	return writeEnvFile(envWrap{env, aliases}, writer, envTemplateUnix)
}
