package main

var (
	envTemplateUnix string
)

func init() {
	envTemplateUnix = `
########################################
#
# This file is generated by goautoenv
#
# Please do not change this file.
#

ENV_DIR={{.Root}}

GOPATH_OLD=${GOPATH}
GOPATH=${ENV_DIR}/.goenv
export GOPATH

_GOAUTOENV_OLD_PATH=${PATH}
PATH=${GOPATH}/bin:${PATH}
export PATH

GOPACKAGE_OLD=${GOPACKAGE}
GOPACKAGE={{.Package}}
export GOPACKAGE

_GOAUTOENV_WORKSPACE=${GOPATH}/src/${GOPACKAGE}

_OLD_GOAUTOENV_PS1="$PS1"
PS1="($GOPACKAGE)\n$PS1"

_GOAUTOENV_GODEP=$(which godep)

godep () {
  pushd $_GOAUTOENV_WORKSPACE > /dev/null 2>&1
  $_GOAUTOENV_GODEP $@
  popd > /dev/null 2>&1
}

deactivate () {
  GOPATH=$GOPATH_OLD
  export GOPATH
  GOPACKAGE=$GOPACKAGE_OLD
  export GOPACKAGE
  PATH=${_GOAUTOENV_OLD_PATH}
  export PATH
  PS1=$_OLD_GOAUTOENV_PS1
  export PS1

  unset -f deactivate
  unset -f godep
  unset _GOAUTOENV_GODEP
}
`
}
