package main

var (
	envTemplatePS string
)

func init() {
	envTemplatePS = `
########################################
#
# This file is generated by goautoenv
#
# Please do not change this file.
#

$script:ENV_DIR = "{{.Root}}"

$global:GOPATH_OLD = $global:GOPATH
$global:GOPATH = "$($script:ENV_DIR)/.goenv"

$global:_GOAUTOENV_OLD_PATH = $global:PATH
$global:PATH = "$($global:GOPATH)/bin;$($global:PATH)"

$global:GOPACKAGE = "{{.Package}}"

$global:_GOAUTOENV_WORKSPACE = "$($global:GOPATH)/src/$GOPACKAGE"

function global:_OLD_GOAUTOENV_PROMPT { "" }
$function:_OLD_GOAUTOENV_PROMPT = $function:prompt
function global:prompt {
  write-host "($global:GOPACKAGE)"
  & $function:_OLD_GOAUTOENV_PROMPT
}

$global:_GOAUTOENV_GODEP=Get-Command godep | Select-Object -ExpandProperty path

function global:godep ($args) {
  pushd $global:_GOAUTOENV_WORKSPACE
  Invoke-Expression "$global:_GOAUTOENV_GODEP $args"
  popd
}

function global:deactivate () {
  $global:GOPATH = $global:GOPATH_OLD
  $global:GOPACKAGE = $global:GOPACKAGE_OLD
  $global:PATH = $global:_GOAUTOENV_OLD_PATH
  $function:prompt = $function:_OLD_GOAUTOENV_PROMPT

  remove-item function:deactivate
  remove-item function:godep
  remove-item global:_GOAUTOENV_GODEP
}
`
}
