package main

var (
	envTemplatePS string
)

func init() {
	envTemplatePS = `
########################################
#
# This file is generated by goautoenv
#
# Please do not change this file.
#

$script:ENV_DIR = "{{.Env.Root}}"

$global:GOPATH_OLD = $global:GOPATH
$global:GOPATH = "$($script:ENV_DIR)/.goenv"

$global:_GOAUTOENV_OLD_PATH = $global:PATH
$global:PATH = "$($global:GOPATH)/bin;$($global:PATH)"

$global:GOPACKAGE = "{{.Env.Package}}"

$global:_GOAUTOENV_WORKSPACE = "$($global:GOPATH)/src/$GOPACKAGE"

function global:_OLD_GOAUTOENV_PROMPT { "" }
$function:_OLD_GOAUTOENV_PROMPT = $function:prompt
function global:prompt {
  write-host "($global:GOPACKAGE)"
  & $function:_OLD_GOAUTOENV_PROMPT
}

{{range $e := .Aliases}}
$global:_GOAUTOENV_{{$e}}=Get-Command {{$e}} | Select-Object -ExpandProperty path

function global:{{$e}} ($args) {
  pushd $global:_GOAUTOENV_WORKSPACE
  Invoke-Expression "$global:_GOAUTOENV_{{$e}} $args"
  popd
}
{{end}}

function global:deactivate () {
  $global:GOPATH = $global:GOPATH_OLD
  $global:GOPACKAGE = $global:GOPACKAGE_OLD
  $global:PATH = $global:_GOAUTOENV_OLD_PATH
  $function:prompt = $function:_OLD_GOAUTOENV_PROMPT

  remove-item function:deactivate
  {{range $e := .Aliases}}
  remove-item function:{{$e}}
  remove-item global:_GOAUTOENV_{{$e}}
  {{end}}
}
`
}
